---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get storage classes
      kubernetes.core.k8s_info:
        api_version: storage.k8s.io/v1
        kind: StorageClass
      register: storage_classes

    - name: Find default storage class
      set_fact:
        default_storage_class: "{{ item.metadata.name }}"
      loop: "{{ storage_classes.resources }}"
      when:
        - "'annotations' in item.metadata"
        - "'storageclass.kubernetes.io/is-default-class' in item.metadata.annotations"
        - "item.metadata.annotations['storageclass.kubernetes.io/is-default-class'] == 'true'"
    - debug: msg="{{ storage_classes }}"
